version: '3.8'

services:
  db-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: quan-test
    ports:
      - "3307:3306"
    expose:
      - 3306

  backend:
    depends_on:
      - db-mysql
    build: 
      context: ../../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

# docker compose -p bookingcare-nodejs-mysql up -d