version: '3.8'

services:
  db-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bookingcare_db
    command: --lower_case_table_names=1
    ports:
      - "3307:3306"
    expose:
      - 3306

  backend:
    depends_on:
      - db-mysql
    build: 
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db-mysql
      - URL_REACT=http://localhost

      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    expose:
      - 8080
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p bookingcare-sern up -d