version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: booking-care
    command: --lower_case_table_names=1
    ports:
      - "3307:3306"